FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build-env
WORKDIR /app

COPY . ./
RUN dotnet restore Discord.Bot.csproj

COPY . ./
RUN dotnet publish -c Release -o out Discord.Bot.csproj

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2

WORKDIR /app
COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "Discord.Bot.dll"]
