// <auto-generated />
using System;
using Discord.Bot.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Discord.Bot.Migrations
{
    [DbContext(typeof(HackContext))]
    [Migration("20190518043854_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Discord.Bot.EF.Data.DiscordUserData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BitcoinAddress");

                    b.Property<string>("BitcoinCashAddress");

                    b.Property<string>("EthereumAddress");

                    b.Property<string>("EthereumClassicAddress");

                    b.Property<DateTimeOffset>("FirstActionTime");

                    b.Property<string>("LitecoinAddress");

                    b.Property<string>("NickName");

                    b.Property<string>("StellarAddress");

                    b.Property<string>("UserGuid");

                    b.Property<string>("WavesAddress");

                    b.HasKey("Id");

                    b.HasIndex("UserGuid")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
